/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package research.file.manage.system.librarian;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Year;
import javax.swing.JOptionPane;
import static research.file.manage.system.constants.DatabaseConnection.getDB_CONNECTION_URL;
import static research.file.manage.system.constants.DatabaseConnection.getDB_PASSWORD;
import static research.file.manage.system.constants.DatabaseConnection.getDB_USERNAME;
import static research.file.manage.system.constants.DatabaseConnection.getJDBC_DRIVER;

/**
 *
 * @author Tuason
 */
public class AddNewBook extends javax.swing.JFrame {

    /**
     * Creates new form AddNewBook
     */
    public AddNewBook() {
        initComponents();
        locationComboBox.setBackground(Color.WHITE);
        statusComboBox.setBackground(Color.WHITE);
        borrowForComboBox.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        accessionNumberField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yearChooser = new com.toedter.calendar.JYearChooser();
        jLabel6 = new javax.swing.JLabel();
        callNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NoOfCopiesField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        subjectsField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        publisherField = new javax.swing.JTextField();
        borrowForComboBox = new javax.swing.JComboBox<>();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel1.setText("Add New Book");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/research/file/manage/system/images/back.png"))); // NOI18N
        backBtn.setToolTipText("Back to Homepage");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        header.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        container.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 150));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setText("Title");
        body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));
        body.add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 230, 30));
        body.add(authorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 230, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setText("Author");
        body.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));
        body.add(accessionNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, 30));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setText("Accession Number");
        body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setText("Year Published");
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        body.add(yearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 30));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel6.setText("Location");
        body.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        body.add(callNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 230, 30));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setText("Call Number");
        body.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel8.setText("Status");
        body.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        body.add(NoOfCopiesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 230, 30));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel9.setText("No. of Copies");
        body.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel10.setText("Subjects");
        body.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));
        body.add(subjectsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 230, 30));

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel11.setText("Publisher");
        body.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        body.add(publisherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 30));

        borrowForComboBox.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        borrowForComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Day", "2 Days", "3 Days", "4 Days", "5 Days", "6 Days", "1 Week" }));
        body.add(borrowForComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 230, 30));

        statusComboBox.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Check-out", "Hold" }));
        body.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 30));

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel12.setText("Borrow for");
        body.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        locationComboBox.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Reference", "Filipiniana", "Industrial Technology", "Reserve", "References", "Education", "Hospitality" }));
        body.add(locationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 230, 30));

        addBtn.setBackground(new java.awt.Color(102, 153, 255));
        addBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add Book");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        body.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 150, 40));

        container.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new LibrarianHomepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String accessionNumber = accessionNumberField.getText();
        String title = titleField.getText();
        String author = authorField.getText();
        int yearPublished = yearChooser.getYear();
        String location = locationComboBox.getSelectedItem().toString();
        String callNumber = callNumberField.getText();
        String status = statusComboBox.getSelectedItem().toString();
        String noOfCopiesStr = NoOfCopiesField.getText();
        int noOfCopies;
        String subjects = subjectsField.getText();
        String publisher = publisherField.getText();
        String borrowFor = borrowForComboBox.getSelectedItem().toString();
        
        // CHECKING
        if(accessionNumber.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter accession number");
            return;
        }
        if(title.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter title");
            return;
        }
        if(location.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter title");
            return;
        }
        if(callNumber.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter cell number");
            return;
        }
        try {
            noOfCopies = Integer.parseInt(noOfCopiesStr);
            if(noOfCopies < 1) {
                JOptionPane.showMessageDialog(rootPane, "Please enter an integer value that is greater than 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Please enter an integer value");
            return;
        }
        if(subjects.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter subject");
            return;
        }
        
        // DATABASE
         Connection connection = null;
        PreparedStatement insertBookStatement = null;
        
        try {
            Class.forName(getJDBC_DRIVER());
            connection = DriverManager.getConnection(getDB_CONNECTION_URL(), getDB_USERNAME(), getDB_PASSWORD());
            
            String insertBookQuery = "INSERT INTO book(accession_name, title, author, year_published, location, call_number, "
                    + "status, noOfCopies, subjects, publisher, borrow_for) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            insertBookStatement = connection.prepareStatement(insertBookQuery);
            insertBookStatement.setString(1, accessionNumber);
            insertBookStatement.setString(2, title);
            insertBookStatement.setString(3, author);
            insertBookStatement.setInt(4, yearPublished);
            insertBookStatement.setString(5, location);
            insertBookStatement.setString(6, callNumber);
            insertBookStatement.setString(7, status);
            insertBookStatement.setInt(8, noOfCopies);
            insertBookStatement.setString(9, subjects);
            insertBookStatement.setString(10, publisher);
            insertBookStatement.setString(11, borrowFor);
            
            if(insertBookStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(rootPane, "Successfully added book");
            }
            
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } finally {
             try {
                if (insertBookStatement != null) {
                    insertBookStatement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NoOfCopiesField;
    private javax.swing.JTextField accessionNumberField;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField authorField;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel body;
    private javax.swing.JComboBox<String> borrowForComboBox;
    private javax.swing.JTextField callNumberField;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JTextField publisherField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField subjectsField;
    private javax.swing.JTextField titleField;
    private com.toedter.calendar.JYearChooser yearChooser;
    // End of variables declaration//GEN-END:variables
}
