/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package research.file.manage.system.librarian;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.TableModel;
import research.file.manage.system.constants.Helper;
import research.file.manage.system.constants.Tables;
import research.file.manage.system.frames.Login;
import research.file.manage.system.frames.Settings;

/**
 *
 * @author Tuason
 */
public class LibrarianHomepage extends javax.swing.JFrame {

    
    public LibrarianHomepage() {
        initComponents();
        addBookBtn.setBackground(Color.WHITE);
        studentsBtn.setBackground(Color.WHITE);
        librarianBtn.setBackground(Color.WHITE);
        
        // TABLES
        Tables.getInstance().setBookTable(bookTable);
        Helper.displayBookTableItems();
        
        bookTable.getTableHeader().setFont(new Font("Monospaced", Font.BOLD, 14));
        bookTable.getTableHeader().setOpaque(false);
        bookTable.getTableHeader().setBackground(new Color(102,153,255));
        
        // KEYPRESS
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LibrarianHomepage.this.keyPressed(evt);
            }
        });
    }
    
    // KEYPRESS
    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            // Simulate a button click when Enter is pressed
            searchBtn.doClick();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        library = new javax.swing.JLabel();
        underline = new javax.swing.JLabel();
        tcc = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        settingsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        studentsBtn = new javax.swing.JButton();
        librarianBtn = new javax.swing.JButton();
        addBookBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        library.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        library.setText("LIBRARY");
        title.add(library, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        underline.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        underline.setText("____________________");
        title.add(underline, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 220, -1));

        tcc.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tcc.setText("TALISAY CITY COLLEGE");
        title.add(tcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/research/file/manage/system/images/tcc logo.png"))); // NOI18N
        title.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        header.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 100));

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/research/file/manage/system/images/gear.png"))); // NOI18N
        settingsBtn.setToolTipText("settings");
        settingsBtn.setBorder(null);
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        header.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, 30));

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/research/file/manage/system/images/logout.png"))); // NOI18N
        logoutBtn.setToolTipText("logout");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        header.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 30));

        container.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        body.setBackground(new java.awt.Color(204, 204, 204));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Accession Number", "Research Title", "Author", "Year Published", "Location", "Call Number", "Status", "No. of Copies", "Subjects", "Publisher", "Borrow for"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        bookTable.setRowHeight(25);
        bookTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookTable);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setMinWidth(200);
            bookTable.getColumnModel().getColumn(0).setMaxWidth(250);
            bookTable.getColumnModel().getColumn(1).setMinWidth(500);
            bookTable.getColumnModel().getColumn(2).setMinWidth(300);
            bookTable.getColumnModel().getColumn(2).setMaxWidth(500);
            bookTable.getColumnModel().getColumn(3).setMinWidth(200);
            bookTable.getColumnModel().getColumn(3).setMaxWidth(250);
            bookTable.getColumnModel().getColumn(4).setMinWidth(300);
            bookTable.getColumnModel().getColumn(4).setMaxWidth(500);
            bookTable.getColumnModel().getColumn(5).setMinWidth(200);
            bookTable.getColumnModel().getColumn(5).setMaxWidth(400);
            bookTable.getColumnModel().getColumn(6).setMinWidth(150);
            bookTable.getColumnModel().getColumn(6).setMaxWidth(200);
            bookTable.getColumnModel().getColumn(7).setMinWidth(150);
            bookTable.getColumnModel().getColumn(7).setMaxWidth(200);
            bookTable.getColumnModel().getColumn(8).setMinWidth(200);
            bookTable.getColumnModel().getColumn(8).setMaxWidth(400);
            bookTable.getColumnModel().getColumn(9).setMinWidth(200);
            bookTable.getColumnModel().getColumn(9).setMaxWidth(400);
            bookTable.getColumnModel().getColumn(10).setMinWidth(100);
            bookTable.getColumnModel().getColumn(10).setMaxWidth(150);
        }

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 760, 360));

        searchField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        searchField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        body.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 200, 30));

        searchBtn.setBackground(new java.awt.Color(102, 153, 255));
        searchBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(51, 51, 51));
        searchBtn.setText("Search");
        searchBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        body.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 90, 30));

        studentsBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        studentsBtn.setText("Students");
        studentsBtn.setToolTipText("User Accounts");
        studentsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        studentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsBtnActionPerformed(evt);
            }
        });
        body.add(studentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        librarianBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        librarianBtn.setText("Librarians");
        librarianBtn.setToolTipText("Admin Accounts");
        librarianBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        librarianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianBtnActionPerformed(evt);
            }
        });
        body.add(librarianBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 130, 30));

        addBookBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        addBookBtn.setText("Add Book");
        addBookBtn.setToolTipText("Add New Book");
        addBookBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });
        body.add(addBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        container.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        new AddNewBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addBookBtnActionPerformed

    private void studentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsBtnActionPerformed
        new Students().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentsBtnActionPerformed

    private void librarianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianBtnActionPerformed
        new Librarian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_librarianBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        new Settings().setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        int index = bookTable.getSelectedRow();
        TableModel model = bookTable.getModel();
        String title = (String) model.getValueAt(index, 1);
        
        new EditBook(title).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookBtn;
    private javax.swing.JPanel body;
    private javax.swing.JTable bookTable;
    private javax.swing.JPanel container;
    private javax.swing.JPanel header;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton librarianBtn;
    private javax.swing.JLabel library;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JButton studentsBtn;
    private javax.swing.JLabel tcc;
    private javax.swing.JPanel title;
    private javax.swing.JLabel underline;
    // End of variables declaration//GEN-END:variables
}
