/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package research.file.manage.system.frames;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static research.file.manage.system.constants.DatabaseConnection.getDB_CONNECTION_URL;
import static research.file.manage.system.constants.DatabaseConnection.getDB_PASSWORD;
import static research.file.manage.system.constants.DatabaseConnection.getDB_USERNAME;
import static research.file.manage.system.constants.DatabaseConnection.getJDBC_DRIVER;

/**
 *
 * @author Tuason
 */
public class StudentSignup extends javax.swing.JFrame {

    /**
     * Creates new form StudentSignup
     */
    public StudentSignup() {
        initComponents();
        
        // KEYPRESS
        StudentSignup.this.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentSignup.this.keyPressed(evt);
            }
        });
        studentIdField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentSignup.this.keyPressed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentSignup.this.keyPressed(evt);
            }
        });
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentSignup.this.keyPressed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentSignup.this.keyPressed(evt);
            }
        });
       
    }
    
    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            // Simulate a button click when Enter is pressed
            createBtn.doClick();
        }
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            // Simulate a button click when Escape is pressed
            cancelBtn.doClick();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        hero = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        heroBg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        createBtn = new javax.swing.JButton();
        books = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hero.setBackground(new java.awt.Color(255, 255, 255));
        hero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        hero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        jLabel2.setText("TREASURES.");
        hero.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel4.setText("I don't have to");
        hero.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        jLabel5.setText("APPLICATION.");
        hero.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel6.setText("look far to find");
        hero.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel7.setText("I discover them");
        hero.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel8.setText("every  time I");
        hero.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel9.setText("visit this");
        hero.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        heroBg.setBackground(new java.awt.Color(255, 255, 255));
        heroBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/research/file/manage/system/images/brown-crumple-recycle-paper-background_35652-2341.jpg"))); // NOI18N
        hero.add(heroBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 500));

        container.add(hero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setText("Full Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        jPanel1.add(studentIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 240, 30));

        cancelBtn.setBackground(new java.awt.Color(134, 103, 90));
        cancelBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 110, 40));

        jLabel14.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel14.setText("CREATE NEW ACCOUNT");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel15.setText("Student ID");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 240, 30));

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel16.setText("Username");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 240, 30));

        createBtn.setBackground(new java.awt.Color(154, 49, 20));
        createBtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("CREATE");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 120, 40));

        books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/research/file/manage/system/images/books.jpg"))); // NOI18N
        jPanel1.add(books, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 210, 130));
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 240, 30));

        container.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 370, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        
        String studentId = studentIdField.getText();
        String name = nameField.getText();
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());

        if(studentId.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your Student ID.");
            return;
        }
        if(name.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your Full Name.");
            return;
        }
        if(username.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your desired username.");
            return;
        }
        if(password.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter your desired password.");
            return;
        }
        
        // DATABASE
        Connection connection = null;
        PreparedStatement selectStatement = null;
        PreparedStatement selectStudentStatement = null;
        PreparedStatement insertStatement = null;
        ResultSet selectRs = null;
        ResultSet selectStudentRs = null;
        
        // CHECK EXISTING - student id and username
        try {
            Class.forName(getJDBC_DRIVER());
            connection = DriverManager.getConnection(getDB_CONNECTION_URL(), getDB_USERNAME(), getDB_PASSWORD());
            
            String selectQuery = "SELECT username, student_id FROM student WHERE username=? OR student_id=?";
            selectStudentStatement = connection.prepareStatement(selectQuery);
            selectStudentStatement.setString(1, username);
            selectStudentStatement.setString(2, studentId);
            selectStudentRs = selectStudentStatement.executeQuery();
            if(selectStudentRs.next()) {
                System.out.println("2");
                // CHECK IF THE USERNAME IS ALREADY EXIST
                if(username.equals(selectStudentRs.getString("username"))) {
                    JOptionPane.showMessageDialog(rootPane, "Username is already exist.");
                    return;
                }
                // CHECK IF THE STUDENT ID IS ALREADY AN ACCOUNT
                if(studentId.equals(selectStudentRs.getString("student_id"))) {
                    JOptionPane.showMessageDialog(rootPane, "This student id has already an account.");
                    return;
                }
            }
            
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } finally {
            try {
                if(selectStudentStatement != null) {
                    selectStudentStatement.close();
                }
                if(selectStudentRs != null) {
                    selectStudentRs.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        
        // RETRIEVE REGISTRAR DATA
        try {
            Class.forName(getJDBC_DRIVER());
            connection = DriverManager.getConnection(getDB_CONNECTION_URL(), getDB_USERNAME(), getDB_PASSWORD());
            String selectQuery = "SELECT * FROM registrar WHERE student_id=?";
            selectStatement = connection.prepareStatement(selectQuery);
            selectStatement.setString(1, studentId);
            selectRs = selectStatement.executeQuery();
            
            // CHECK IF THE STUDENT ID EXIST
            if(selectRs.next()) {
                // CREATE ACCOUNT
                String insertQuery = "INSERT INTO student (student_id, name, username, password) VALUE (?,?,?,?)";
                insertStatement = connection.prepareStatement(insertQuery);
                insertStatement.setString(1, studentId);
                insertStatement.setString(2, name);
                insertStatement.setString(3, username);
                insertStatement.setString(4, password);

                if(insertStatement.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Successfully created new account.");
                    new Login().setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Student ID is incorrect. Please try again.");
            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
             try {
                if (selectRs != null) {
                    selectRs.close();
                }
                if (selectStatement != null) {
                    selectStatement.close();
                }
                if (insertStatement != null) {
                    insertStatement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_createBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel books;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel container;
    private javax.swing.JButton createBtn;
    private javax.swing.JPanel hero;
    private javax.swing.JLabel heroBg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
