/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package research.file.management.system.pages;

import javax.swing.JOptionPane;
import static research.file.management.system.images.database.Helper.isAdminLoggedIn;
import static research.file.management.system.images.database.Helper.isStudentLoggedIn;
import research.file.management.system.images.database.UserData;

/**
 *
 * @author Tuason
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quote = new javax.swing.JLabel();
        quote1 = new javax.swing.JLabel();
        quote2 = new javax.swing.JLabel();
        quote4 = new javax.swing.JLabel();
        quote3 = new javax.swing.JLabel();
        quote5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        quoteBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quote.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        quote.setText("- Albert Einstein");
        jPanel1.add(quote, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        quote1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        quote1.setText("\"If we know what were");
        jPanel1.add(quote1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        quote2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        quote2.setText("called");
        jPanel1.add(quote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        quote4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        quote4.setText("https://talisaycitycollege.netlify.app/");
        jPanel1.add(quote4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        quote3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        quote3.setText("doing, it wouldn't be");
        jPanel1.add(quote3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        quote5.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        quote5.setText("RESEARCH\"");
        jPanel1.add(quote5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        usernameField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 220, 30));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        passwordField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 220, 30));

        loginBtn.setBackground(new java.awt.Color(204, 204, 204));
        loginBtn.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 110, 40));

        showPasswordCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 360, 500));

        quoteBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/research/inventory/management/system/images/pexels-taryn-elliott-4440123.jpg"))); // NOI18N
        jPanel1.add(quoteBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        String username = usernameField.getText();
        String password = passwordField.getText();
        
        if(isStudentLoggedIn(username, password)) {
            this.dispose();
            new Student().setVisible(true);
            UserData.getInstance().setUserData(username, password);
        } else if(isAdminLoggedIn(username, password)) {
            this.dispose();
            new Books().setVisible(true);
            UserData.getInstance().setUserData(username, password);
        } else{
            JOptionPane.showMessageDialog(this, "Incorrect username or password.");
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if (showPasswordCheckBox.isSelected()){
            passwordField.setEchoChar((char)0);
        } else{
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel quote;
    private javax.swing.JLabel quote1;
    private javax.swing.JLabel quote2;
    private javax.swing.JLabel quote3;
    private javax.swing.JLabel quote4;
    private javax.swing.JLabel quote5;
    private javax.swing.JLabel quoteBg;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
